### ISSUE TITLE
I am looking forward to using this YouTube site.

### ISSUE THREAD

**Issue by KaineRecycler** [hemang-2001/smartube#7]
Hi my name is Kaine Dube and I just want to find out if that I can use this website that has the YouTube API from Google and I have a question about using smartube app for my windows 11 PC computer and first of all I am looking for a way to view and watch deleted unlisted private content from within using smartube and does this platform has all the content from YouTube ranging from deleted unlisted private current content because If this site has it then I want to try out this app on my windows 11 PC computer for my interest in using smartube for my bedroom windows 11 PC computer that I have currently on the floor charging beside my bed and in front of my nightstand and well so that concludes my most first question about your smartube app that you had made for users to watch YouTube even more with your apps new features but I would have to rather just use my current official YouTube app on my PC or just replace it current official YouTube app with smartube app for my windows 11 PC computer for my interest so please feel free and message me back on GitHub if you have a solution that you could make for me before I can start using the smartube app for my interest on my bedroom PC computer for my first time please. From Kaine Dube

**Comment by hemang-2001** [comment]
Hi Kaine,

Thanks for reaching out about Smartube. Unfortunately, Smartube doesn't provide access to deleted, unlisted, or private YouTube content. It's best to stick with the official YouTube app for now. If you have any other questions, feel free to ask.

Best,
Hemang Bairwa

**Comment by hemang-2001** [comment]
Hi Kaine,

Thanks for reaching out about Smartube. Unfortunately, Smartube doesn't provide access to deleted, unlisted, or private YouTube content. It's best to stick with the official YouTube app for now. If you have any other questions, feel free to ask.

Best,
Hemang Bairwa

**Comment by hemang-2001** [comment]
Hi Kaine,

Thanks for reaching out about Smartube. Unfortunately, Smartube doesn't provide access to deleted, unlisted, or private YouTube content. It's best to stick with the official YouTube app for now. If you have any other questions, feel free to ask.

Best,
Hemang Bairwa
